name: Delta deploy to PROD (on PR close)

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  Delta-Deploy-PROD:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # Esegui solo se la PR è stata effettivamente unita a main
    steps:
      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          sf --version

      # Install SFDX-Git-Delta
      - name: Install sfdx-git-delta
        run: |
          echo y | sf plugins install sfdx-git-delta
          sf plugins

      # Install utilities
      - name: Install utilities
        run: |
          pip install yq
          xq --version

      # Checkout the main branch (perché il codice è già stato mergiato lì)
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Assicuriamoci di avere la cronologia completa

      # Determina il branch della PR chiusa
      - name: Determina il branch della PR chiusa
        run: |
          echo "Branch sorgente della PR chiusa: ${{ github.event.pull_request.head.ref }}"
          echo "SOURCE_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      # Fetch del branch della PR per calcolare il delta
      - name: Fetch PR branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}

      # Trova il commit base tra main e il branch della PR
      - name: Compute common ancestor commit
        id: compute-ancestor
        run: |
          export BASE_COMMIT=$(git merge-base origin/main HEAD)
          echo "BASE_COMMIT=$BASE_COMMIT" >> $GITHUB_ENV
          echo "Base commit: $BASE_COMMIT"

      # Authenticate to Salesforce Org
      - name: Authenticate to Org
        run: |
          echo ${{ secrets.SFDXAUTHURL_PROD }} > ./SFDX_URL.txt
          sf org login sfdx-url --sfdx-url-file ./SFDX_URL.txt --set-default

      # Calcola il delta con sfdx-git-delta
      - name: Compute delta using sfdx-git-delta
        run: |
          sf sgd:source:delta --to "HEAD" --from ${{ env.BASE_COMMIT }} --output-dir "." -i .forceignore
          echo "--- package.xml generato con le modifiche rilevate ---"
          cat package/package.xml

      # Esegui il deploy su PROD
      - name: Deploy to PROD
        run: |
          sf project deploy start --manifest package/package.xml
          echo "--- Deployment to PROD Completed ---"
