name: Delta deploy to PROD (on new commits on the `main` branch)

on:
  push:
    branches:
      - main

jobs:
  Delta-Deploy-PLAYGROUND:
    runs-on: ubuntu-latest
    steps:
      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          sf --version

      # Install plugins
      - name: Install plugins
        run: |
          echo y | sf plugins install @salesforce/plugin-devops-center
          sf plugins

      # Install utilities
      - name: Install utilities
        run: |
         pip install yq
         xq --version

      # Checkout the main branch (the branch that received the push)
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Assicuriamoci di avere tutta la cronologia per il confronto dei commit

      # Compute the common ancestor commit between main and the pushed branch
      - name: Compute common ancestor commit
        id: compute-ancestor
        run: |
          # Troviamo il commit base tra main e il branch di origine
          export BASE_COMMIT=$(git merge-base origin/main HEAD)
          echo "BASE_COMMIT=$BASE_COMMIT" >> $GITHUB_ENV
          echo "Base commit: $BASE_COMMIT"

      # Eseguiamo il diff tra main e il commit base
      - name: Compute delta (diff between HEAD of main and common ancestor)
        run: |
          # Otteniamo i file modificati tra main e il commit base
          git diff --name-only ${{ env.BASE_COMMIT }} HEAD > changed_files.txt
          echo "Changed files between main and branch:" 
          cat changed_files.txt

      # Authenticate to target org
      - name: "Authenticate to Org"
        run: |
          echo ${{ secrets.SFDXAUTHURL_UAT }} > ./SFDX_URL.txt
          sf org login sfdx-url --sfdx-url-file ./SFDX_URL.txt --set-default

      # Compute delta deploy based on changed files
      - name: "Delta deploy"
        run: |
          # Genera il package.xml con i file modificati
          sf sgd:source:delta --to "HEAD" --from ${{ env.BASE_COMMIT }} --output-dir "." -i .forceignore
          echo "--- package.xml generated with added and modified metadata ---"
          cat package/package.xml
          echo
          echo "--- Apex Tests to be executed ---"
          
          export APEX_CLASSES=$(xq . < package/package.xml | jq '.Package.types | [.] | flatten | map(select(.name=="ApexClass")) | .[] | .members | [.] | flatten | map(select(. | index("*") | not)) | unique | join(" ")' -r)
          echo $APEX_CLASSES
          echo
          echo "--- Delta Deploy ---"
          
          # Verifica se ci sono test da eseguire
          if [ -z "$APEX_CLASSES" ]; then
            sf project deploy start --manifest package/package.xml --wait 30
          else
            echo "APEX_CLASSES variable is: $APEX_CLASSES"
            sf project deploy start --manifest package/package.xml --wait 30 --test-level RunSpecifiedTests --tests $APEX_CLASSES
          fi
