name: Delta deploy to PROD (on new commits on the `main` branch)

on:
  push:
    branches:
      - main

jobs:
  Delta-Deploy-PROD:
    runs-on: ubuntu-latest
    steps:
      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          sf --version

      # Install SFDX-Git-Delta
      - name: Install sfdx-git-delta
        run: |
          echo y | sf plugins install sfdx-git-delta
          sf plugins

      # Install utilities
      - name: Install utilities
        run: |
          pip install yq
          xq --version

      # Checkout the main branch first
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure we have full history for comparison

      # Create a temporary branch to avoid conflicts with 'develop'
      - name: Create a temporary branch for PR
        run: |
          git checkout -b temp-branch
          echo "Temporary branch created to avoid conflicts"

      # Fetch the PR source branch into this temporary branch
      - name: Fetch the PR source branch
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/head:temp-branch-pr
          git checkout temp-branch-pr
          echo "Checked out the PR branch"

      # Authenticate to target org
      - name: Authenticate to Org
        run: |
          echo ${{ secrets.SFDXAUTHURL_PROD }} > ./SFDX_URL.txt
          sf org login sfdx-url --sfdx-url-file ./SFDX_URL.txt --set-default

      # Compute the common ancestor commit between main and the PR source branch
      - name: Compute common ancestor commit
        id: compute-ancestor
        run: |
          export BASE_COMMIT=$(git merge-base origin/main HEAD)
          echo "BASE_COMMIT=$BASE_COMMIT" >> $GITHUB_ENV
          echo "Base commit: $BASE_COMMIT"

      # Run delta with sfdx-git-delta to generate package.xml with changed files
      - name: Compute delta using sfdx-git-delta
        run: |
          sf sgd:source:delta --to "HEAD" --from ${{ env.BASE_COMMIT }} --output-dir "." -i .forceignore
          echo "--- package.xml generated with added and modified metadata ---"
          cat package/package.xml
          echo

      # Deploy to PROD
      - name: Deploy to PROD
        run: |
          sf project deploy start --manifest package/package.xml
          echo "--- Deployment to PROD Completed ---"
