name: Delta deploy to UAT

on:
  push:
    branches:    
      - main

jobs:
  Delta-Deploy-UAT:
    runs-on:  ubuntu-latest
    steps:
      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          sf --version
      # SFDX-Git-Delta
      - name: Install plugins
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
          sf plugins
      # Install utilities
      - name: Install utilities
        run: |
         pip install yq
         xq --version
      # Checkout the code in the pull request
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Authenticate to target org
      - name: "Authenticate to Org"
        run: |
          echo ${{ secrets.SFDXAUTHURL_UAT }} > ./SFDX_URL.txt
          sf org login sfdx-url --sfdx-url-file ./SFDX_URL.txt --set-default
      # Delta deploy
      - name: "Delta deploy"
        run: |
          sf sgd:source:delta --to "HEAD" --from "HEAD~1" --output "." -i .forceignore
          echo "--- package.xml generated with added and modified metadata ---"
          cat package/package.xml
          echo
          echo "--- Apex Tests to be executed ---"
          export APEX_CLASSES=$(xq . < package/package.xml | jq '.Package.types | [.] | flatten | map(select(.name=="ApexClass")) | .[] | .members | [.] | flatten | map(select(. | index("*") | not)) | unique | join(",")' -r)
          echo $APEX_CLASSES
          echo
          echo "--- Delta Deploy ---"
          if [ -z "$APEX_CLASSES" ]; then
            sf project deploy start --manifest package/package.xml --wait 30
          else
            sf project deploy start --manifest package/package.xml --wait 30 --test-level RunSpecifiedTests --tests "$APEX_CLASSES"
          fi