name: PR - Deploy delta to MAIN (PROD Org)

on:
  pull_request_review:
    types: [submitted]

jobs:
  Code-Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - name: Install PMD
        run: wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.51.0/pmd-bin-6.51.0.zip && unzip pmd-bin-6.51.0.zip
      - name: Execute PMD
        run: pmd-bin-6.51.0/bin/run.sh pmd --minimum-priority 2 -R apex-rules.xml -d force-app -f text -l apex

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        run: echo "${{ toJSON(github.event) }}"

      - name: Check approval and target branch
        if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'
        run: echo "✅ PR Approved for Main, proceeding with deployment"

      - name: Install Salesforce CLI
        if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'
        run: |
          npm install @salesforce/cli --global
          sf --version

      - name: Install plugins
        if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'
        run: |
          echo y | sf plugins install @salesforce/plugin-devops-center
          sf plugins

      - name: Install utilities
        if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'
        run: |
         pip install yq
         xq --version

      - name: Checkout
        if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Compute delta
        if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'
        run: |
          export BASE_COMMIT=$(git merge-base origin/main HEAD)
          sf project deploy start --source-dir force-app --source-dir $(git diff --name-only $BASE_COMMIT HEAD)
          echo "--- Deployment Completed Successfully ---"
